# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - name: ssh into VPS and build latest version
      #   uses: garygrossgarten/github-action-ssh@release
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     privateKey: ${{ secrets.KEY }}
      #     command: ls -hal
      #     # port: ${{ secrets.PORT }}
      #     # script_stop: true
      #     # debug: true
      #     # script: whoami
      #     # script: |
      #     #   cd ~/website-source
      #     #   eval $(ssh-agent -s) && ssh-add ~/.ssh/id_github
      #     #   git pull
      #     #   npm run publish

      - name: Run a one-line script
        run: echo Hello, world!

      # - name: Run a multi-line script
      #   run: |
      #     npm run lint
